name: Run integration tests

# temporary disable integration test
on:
  push:
    branches: [master, main]
  pull_request:

env:
  PYTHON_DEFAULT_VERSION: "3.11"
  AWS_DEFAULT_REGION: "us-east-1"
  S3_BUCKET_NAME: "compute-horde-integration-tests"

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.x"
          enable-cache: true
      - name: Start all services
        run: local_stack/run_and_await_readiness.sh /tmp/integration_test_logs/

      - name: test_hello_world_job
        working-directory: ./local_stack
        run: uv run ./send_hello_world_job.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.INTEGRATION_TESTS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.INTEGRATION_TESTS_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
          S3_BUCKET_NAME: ${{ env.S3_BUCKET_NAME }}

      - name: test_simple_job
        working-directory: ./local_stack
        run: uv run ./send_several_subsequent_jobs.py 5

      - name: Upload integration test logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-logs
          path: /tmp/integration_test_logs/*.log

